// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: btab.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BTABClient is the client API for BTAB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BTABClient interface {
	// Sends a greeting
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type bTABClient struct {
	cc grpc.ClientConnInterface
}

func NewBTABClient(cc grpc.ClientConnInterface) BTABClient {
	return &bTABClient{cc}
}

func (c *bTABClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/rpc.BTAB/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BTABServer is the server API for BTAB service.
// All implementations must embed UnimplementedBTABServer
// for forward compatibility
type BTABServer interface {
	// Sends a greeting
	Ping(context.Context, *PingRequest) (*PingReply, error)
	MustEmbedUnimplementedBTABServer()
}

// UnimplementedBTABServer must be embedded to have forward compatible implementations.
type UnimplementedBTABServer struct {
}

func (UnimplementedBTABServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBTABServer) MustEmbedUnimplementedBTABServer() {}

// UnsafeBTABServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BTABServer will
// result in compilation errors.
type UnsafeBTABServer interface {
	MustEmbedUnimplementedBTABServer()
}

func RegisterBTABServer(s grpc.ServiceRegistrar, srv BTABServer) {
	s.RegisterService(&BTAB_ServiceDesc, srv)
}

func _BTAB_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BTABServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.BTAB/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BTABServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BTAB_ServiceDesc is the grpc.ServiceDesc for BTAB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BTAB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.BTAB",
	HandlerType: (*BTABServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BTAB_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "btab.proto",
}
