# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engines.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_pb2 as msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rengines.proto\x12\x03rpc\x1a\tmsg.proto\"\x13\n\x11\x43heckAliveRequest\"5\n\x0f\x43heckAliveReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"+\n\nSetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\".\n\x08SetReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"\x1a\n\nGetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\x08GetReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"\x1d\n\nRunRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\".\n\x08RunReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType2\xc2\x01\n\x07\x45ngines\x12<\n\nCheckAlive\x12\x16.rpc.CheckAliveRequest\x1a\x14.rpc.CheckAliveReply\"\x00\x12\'\n\x03Set\x12\x0f.rpc.SetRequest\x1a\r.rpc.SetReply\"\x00\x12\'\n\x03Get\x12\x0f.rpc.GetRequest\x1a\r.rpc.GetReply\"\x00\x12\'\n\x03Run\x12\x0f.rpc.RunRequest\x1a\r.rpc.RunReply\"\x00\x42\x04Z\x02./b\x06proto3')



_CHECKALIVEREQUEST = DESCRIPTOR.message_types_by_name['CheckAliveRequest']
_CHECKALIVEREPLY = DESCRIPTOR.message_types_by_name['CheckAliveReply']
_SETREQUEST = DESCRIPTOR.message_types_by_name['SetRequest']
_SETREPLY = DESCRIPTOR.message_types_by_name['SetReply']
_GETREQUEST = DESCRIPTOR.message_types_by_name['GetRequest']
_GETREPLY = DESCRIPTOR.message_types_by_name['GetReply']
_RUNREQUEST = DESCRIPTOR.message_types_by_name['RunRequest']
_RUNREPLY = DESCRIPTOR.message_types_by_name['RunReply']
CheckAliveRequest = _reflection.GeneratedProtocolMessageType('CheckAliveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKALIVEREQUEST,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.CheckAliveRequest)
  })
_sym_db.RegisterMessage(CheckAliveRequest)

CheckAliveReply = _reflection.GeneratedProtocolMessageType('CheckAliveReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKALIVEREPLY,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.CheckAliveReply)
  })
_sym_db.RegisterMessage(CheckAliveReply)

SetRequest = _reflection.GeneratedProtocolMessageType('SetRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETREQUEST,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SetRequest)
  })
_sym_db.RegisterMessage(SetRequest)

SetReply = _reflection.GeneratedProtocolMessageType('SetReply', (_message.Message,), {
  'DESCRIPTOR' : _SETREPLY,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SetReply)
  })
_sym_db.RegisterMessage(SetReply)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetReply = _reflection.GeneratedProtocolMessageType('GetReply', (_message.Message,), {
  'DESCRIPTOR' : _GETREPLY,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.GetReply)
  })
_sym_db.RegisterMessage(GetReply)

RunRequest = _reflection.GeneratedProtocolMessageType('RunRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNREQUEST,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RunRequest)
  })
_sym_db.RegisterMessage(RunRequest)

RunReply = _reflection.GeneratedProtocolMessageType('RunReply', (_message.Message,), {
  'DESCRIPTOR' : _RUNREPLY,
  '__module__' : 'engines_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RunReply)
  })
_sym_db.RegisterMessage(RunReply)

_ENGINES = DESCRIPTOR.services_by_name['Engines']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _CHECKALIVEREQUEST._serialized_start=33
  _CHECKALIVEREQUEST._serialized_end=52
  _CHECKALIVEREPLY._serialized_start=54
  _CHECKALIVEREPLY._serialized_end=107
  _SETREQUEST._serialized_start=109
  _SETREQUEST._serialized_end=152
  _SETREPLY._serialized_start=154
  _SETREPLY._serialized_end=200
  _GETREQUEST._serialized_start=202
  _GETREQUEST._serialized_end=228
  _GETREPLY._serialized_start=230
  _GETREPLY._serialized_end=276
  _RUNREQUEST._serialized_start=278
  _RUNREQUEST._serialized_end=307
  _RUNREPLY._serialized_start=309
  _RUNREPLY._serialized_end=355
  _ENGINES._serialized_start=358
  _ENGINES._serialized_end=552
# @@protoc_insertion_point(module_scope)
