// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: engines.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EnginesClient is the client API for Engines service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnginesClient interface {
	CheckAlive(ctx context.Context, in *CheckAliveRequest, opts ...grpc.CallOption) (*CheckAliveReply, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetReply, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error)
}

type enginesClient struct {
	cc grpc.ClientConnInterface
}

func NewEnginesClient(cc grpc.ClientConnInterface) EnginesClient {
	return &enginesClient{cc}
}

func (c *enginesClient) CheckAlive(ctx context.Context, in *CheckAliveRequest, opts ...grpc.CallOption) (*CheckAliveReply, error) {
	out := new(CheckAliveReply)
	err := c.cc.Invoke(ctx, "/rpc.Engines/CheckAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enginesClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetReply, error) {
	out := new(SetReply)
	err := c.cc.Invoke(ctx, "/rpc.Engines/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enginesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/rpc.Engines/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enginesClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunReply, error) {
	out := new(RunReply)
	err := c.cc.Invoke(ctx, "/rpc.Engines/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnginesServer is the server API for Engines service.
// All implementations must embed UnimplementedEnginesServer
// for forward compatibility
type EnginesServer interface {
	CheckAlive(context.Context, *CheckAliveRequest) (*CheckAliveReply, error)
	Set(context.Context, *SetRequest) (*SetReply, error)
	Get(context.Context, *GetRequest) (*GetReply, error)
	Run(context.Context, *RunRequest) (*RunReply, error)
	mustEmbedUnimplementedEnginesServer()
}

// UnimplementedEnginesServer must be embedded to have forward compatible implementations.
type UnimplementedEnginesServer struct {
}

func (UnimplementedEnginesServer) CheckAlive(context.Context, *CheckAliveRequest) (*CheckAliveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAlive not implemented")
}
func (UnimplementedEnginesServer) Set(context.Context, *SetRequest) (*SetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedEnginesServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEnginesServer) Run(context.Context, *RunRequest) (*RunReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedEnginesServer) mustEmbedUnimplementedEnginesServer() {}

// UnsafeEnginesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnginesServer will
// result in compilation errors.
type UnsafeEnginesServer interface {
	mustEmbedUnimplementedEnginesServer()
}

func RegisterEnginesServer(s grpc.ServiceRegistrar, srv EnginesServer) {
	s.RegisterService(&Engines_ServiceDesc, srv)
}

func _Engines_CheckAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnginesServer).CheckAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Engines/CheckAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnginesServer).CheckAlive(ctx, req.(*CheckAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engines_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnginesServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Engines/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnginesServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engines_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnginesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Engines/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnginesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engines_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnginesServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Engines/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnginesServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Engines_ServiceDesc is the grpc.ServiceDesc for Engines service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engines_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Engines",
	HandlerType: (*EnginesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAlive",
			Handler:    _Engines_CheckAlive_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Engines_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Engines_Get_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _Engines_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engines.proto",
}
