# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msg_pb2 as msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x03rpc\x1a\tmsg.proto\",\n\rSetPRSRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"1\n\x0bSetPRSReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"\x18\n\x16\x43heckConnectionRequest\":\n\x14\x43heckConnectionReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"9\n\x13SetDateRangeRequest\x12\x11\n\tdateStart\x18\x01 \x01(\x03\x12\x0f\n\x07\x64\x61teEnd\x18\x02 \x01(\x03\"7\n\x11SetDateRangeReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"$\n\x11SetVersionRequest\x12\x0f\n\x07version\x18\x01 \x01(\x03\"5\n\x0fSetVersionReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\" \n\rSubmitRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"1\n\x0bSubmitReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\",\n\x0bSaveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"/\n\tSaveReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"#\n\x13SubmitByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x11SubmitByNameReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType2\xab\x03\n\x06Search\x12\x30\n\x06SetPRS\x12\x12.rpc.SetPRSRequest\x1a\x10.rpc.SetPRSReply\"\x00\x12K\n\x0f\x43heckConnection\x12\x1b.rpc.CheckConnectionRequest\x1a\x19.rpc.CheckConnectionReply\"\x00\x12\x42\n\x0cSetDateRange\x12\x18.rpc.SetDateRangeRequest\x1a\x16.rpc.SetDateRangeReply\"\x00\x12<\n\nSetVersion\x12\x16.rpc.SetVersionRequest\x1a\x14.rpc.SetVersionReply\"\x00\x12\x30\n\x06Submit\x12\x12.rpc.SubmitRequest\x1a\x10.rpc.SubmitReply\"\x00\x12*\n\x04Save\x12\x10.rpc.SaveRequest\x1a\x0e.rpc.SaveReply\"\x00\x12\x42\n\x0cSubmitByName\x12\x18.rpc.SubmitByNameRequest\x1a\x16.rpc.SubmitByNameReply\"\x00\x42\x04Z\x02./b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _SETPRSREQUEST._serialized_start=32
  _SETPRSREQUEST._serialized_end=76
  _SETPRSREPLY._serialized_start=78
  _SETPRSREPLY._serialized_end=127
  _CHECKCONNECTIONREQUEST._serialized_start=129
  _CHECKCONNECTIONREQUEST._serialized_end=153
  _CHECKCONNECTIONREPLY._serialized_start=155
  _CHECKCONNECTIONREPLY._serialized_end=213
  _SETDATERANGEREQUEST._serialized_start=215
  _SETDATERANGEREQUEST._serialized_end=272
  _SETDATERANGEREPLY._serialized_start=274
  _SETDATERANGEREPLY._serialized_end=329
  _SETVERSIONREQUEST._serialized_start=331
  _SETVERSIONREQUEST._serialized_end=367
  _SETVERSIONREPLY._serialized_start=369
  _SETVERSIONREPLY._serialized_end=422
  _SUBMITREQUEST._serialized_start=424
  _SUBMITREQUEST._serialized_end=456
  _SUBMITREPLY._serialized_start=458
  _SUBMITREPLY._serialized_end=507
  _SAVEREQUEST._serialized_start=509
  _SAVEREQUEST._serialized_end=553
  _SAVEREPLY._serialized_start=555
  _SAVEREPLY._serialized_end=602
  _SUBMITBYNAMEREQUEST._serialized_start=604
  _SUBMITBYNAMEREQUEST._serialized_end=639
  _SUBMITBYNAMEREPLY._serialized_start=641
  _SUBMITBYNAMEREPLY._serialized_end=696
  _SEARCH._serialized_start=699
  _SEARCH._serialized_end=1126
# @@protoc_insertion_point(module_scope)
