# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\x12\x03rpc\"K\n\x0cResponseType\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x03\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0e\n\x06Result\x18\x03 \x01(\t\x12\x0c\n\x04Type\x18\x04 \x01(\tB\x04Z\x02./b\x06proto3')



_RESPONSETYPE = DESCRIPTOR.message_types_by_name['ResponseType']
ResponseType = _reflection.GeneratedProtocolMessageType('ResponseType', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETYPE,
  '__module__' : 'msg_pb2'
  # @@protoc_insertion_point(class_scope:rpc.ResponseType)
  })
_sym_db.RegisterMessage(ResponseType)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _RESPONSETYPE._serialized_start=18
  _RESPONSETYPE._serialized_end=93
# @@protoc_insertion_point(module_scope)
