# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import msg_pb2 as msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x03rpc\x1a\tmsg.proto\",\n\rSetPRSRequest\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"1\n\x0bSetPRSReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"\x18\n\x16\x43heckConnectionRequest\":\n\x14\x43heckConnectionReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"9\n\x13SetDateRangeRequest\x12\x11\n\tdateStart\x18\x01 \x01(\x03\x12\x0f\n\x07\x64\x61teEnd\x18\x02 \x01(\x03\"7\n\x11SetDateRangeReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\" \n\rSubmitRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"1\n\x0bSubmitReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\",\n\x0bSaveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"/\n\tSaveReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType\"#\n\x13SubmitByNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"7\n\x11SubmitByNameReply\x12\"\n\x07message\x18\x01 \x01(\x0b\x32\x11.rpc.ResponseType2\xed\x02\n\x06Search\x12\x30\n\x06SetPRS\x12\x12.rpc.SetPRSRequest\x1a\x10.rpc.SetPRSReply\"\x00\x12K\n\x0f\x43heckConnection\x12\x1b.rpc.CheckConnectionRequest\x1a\x19.rpc.CheckConnectionReply\"\x00\x12\x42\n\x0cSetDateRange\x12\x18.rpc.SetDateRangeRequest\x1a\x16.rpc.SetDateRangeReply\"\x00\x12\x30\n\x06Submit\x12\x12.rpc.SubmitRequest\x1a\x10.rpc.SubmitReply\"\x00\x12*\n\x04Save\x12\x10.rpc.SaveRequest\x1a\x0e.rpc.SaveReply\"\x00\x12\x42\n\x0cSubmitByName\x12\x18.rpc.SubmitByNameRequest\x1a\x16.rpc.SubmitByNameReply\"\x00\x42\x04Z\x02./b\x06proto3')



_SETPRSREQUEST = DESCRIPTOR.message_types_by_name['SetPRSRequest']
_SETPRSREPLY = DESCRIPTOR.message_types_by_name['SetPRSReply']
_CHECKCONNECTIONREQUEST = DESCRIPTOR.message_types_by_name['CheckConnectionRequest']
_CHECKCONNECTIONREPLY = DESCRIPTOR.message_types_by_name['CheckConnectionReply']
_SETDATERANGEREQUEST = DESCRIPTOR.message_types_by_name['SetDateRangeRequest']
_SETDATERANGEREPLY = DESCRIPTOR.message_types_by_name['SetDateRangeReply']
_SUBMITREQUEST = DESCRIPTOR.message_types_by_name['SubmitRequest']
_SUBMITREPLY = DESCRIPTOR.message_types_by_name['SubmitReply']
_SAVEREQUEST = DESCRIPTOR.message_types_by_name['SaveRequest']
_SAVEREPLY = DESCRIPTOR.message_types_by_name['SaveReply']
_SUBMITBYNAMEREQUEST = DESCRIPTOR.message_types_by_name['SubmitByNameRequest']
_SUBMITBYNAMEREPLY = DESCRIPTOR.message_types_by_name['SubmitByNameReply']
SetPRSRequest = _reflection.GeneratedProtocolMessageType('SetPRSRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETPRSREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SetPRSRequest)
  })
_sym_db.RegisterMessage(SetPRSRequest)

SetPRSReply = _reflection.GeneratedProtocolMessageType('SetPRSReply', (_message.Message,), {
  'DESCRIPTOR' : _SETPRSREPLY,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SetPRSReply)
  })
_sym_db.RegisterMessage(SetPRSReply)

CheckConnectionRequest = _reflection.GeneratedProtocolMessageType('CheckConnectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKCONNECTIONREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.CheckConnectionRequest)
  })
_sym_db.RegisterMessage(CheckConnectionRequest)

CheckConnectionReply = _reflection.GeneratedProtocolMessageType('CheckConnectionReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKCONNECTIONREPLY,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.CheckConnectionReply)
  })
_sym_db.RegisterMessage(CheckConnectionReply)

SetDateRangeRequest = _reflection.GeneratedProtocolMessageType('SetDateRangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETDATERANGEREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SetDateRangeRequest)
  })
_sym_db.RegisterMessage(SetDateRangeRequest)

SetDateRangeReply = _reflection.GeneratedProtocolMessageType('SetDateRangeReply', (_message.Message,), {
  'DESCRIPTOR' : _SETDATERANGEREPLY,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SetDateRangeReply)
  })
_sym_db.RegisterMessage(SetDateRangeReply)

SubmitRequest = _reflection.GeneratedProtocolMessageType('SubmitRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SubmitRequest)
  })
_sym_db.RegisterMessage(SubmitRequest)

SubmitReply = _reflection.GeneratedProtocolMessageType('SubmitReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITREPLY,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SubmitReply)
  })
_sym_db.RegisterMessage(SubmitReply)

SaveRequest = _reflection.GeneratedProtocolMessageType('SaveRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SaveRequest)
  })
_sym_db.RegisterMessage(SaveRequest)

SaveReply = _reflection.GeneratedProtocolMessageType('SaveReply', (_message.Message,), {
  'DESCRIPTOR' : _SAVEREPLY,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SaveReply)
  })
_sym_db.RegisterMessage(SaveReply)

SubmitByNameRequest = _reflection.GeneratedProtocolMessageType('SubmitByNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITBYNAMEREQUEST,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SubmitByNameRequest)
  })
_sym_db.RegisterMessage(SubmitByNameRequest)

SubmitByNameReply = _reflection.GeneratedProtocolMessageType('SubmitByNameReply', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITBYNAMEREPLY,
  '__module__' : 'search_pb2'
  # @@protoc_insertion_point(class_scope:rpc.SubmitByNameReply)
  })
_sym_db.RegisterMessage(SubmitByNameReply)

_SEARCH = DESCRIPTOR.services_by_name['Search']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002./'
  _SETPRSREQUEST._serialized_start=32
  _SETPRSREQUEST._serialized_end=76
  _SETPRSREPLY._serialized_start=78
  _SETPRSREPLY._serialized_end=127
  _CHECKCONNECTIONREQUEST._serialized_start=129
  _CHECKCONNECTIONREQUEST._serialized_end=153
  _CHECKCONNECTIONREPLY._serialized_start=155
  _CHECKCONNECTIONREPLY._serialized_end=213
  _SETDATERANGEREQUEST._serialized_start=215
  _SETDATERANGEREQUEST._serialized_end=272
  _SETDATERANGEREPLY._serialized_start=274
  _SETDATERANGEREPLY._serialized_end=329
  _SUBMITREQUEST._serialized_start=331
  _SUBMITREQUEST._serialized_end=363
  _SUBMITREPLY._serialized_start=365
  _SUBMITREPLY._serialized_end=414
  _SAVEREQUEST._serialized_start=416
  _SAVEREQUEST._serialized_end=460
  _SAVEREPLY._serialized_start=462
  _SAVEREPLY._serialized_end=509
  _SUBMITBYNAMEREQUEST._serialized_start=511
  _SUBMITBYNAMEREQUEST._serialized_end=546
  _SUBMITBYNAMEREPLY._serialized_start=548
  _SUBMITBYNAMEREPLY._serialized_end=603
  _SEARCH._serialized_start=606
  _SEARCH._serialized_end=971
# @@protoc_insertion_point(module_scope)
